### User sign up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
    "name": "ken",
    "phone": 122121212,
    "email": "as@asd.com",
    "password": "bleh"
}

### User sign in endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
    "email": "as@asd.com",
    "password": "bleh"
}

### Get a user profile endpoint
GET http://localhost:3001/v1/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFzQGFzZC5jb20iLCJpYXQiOjE3MDU0NTE3ODMsImV4cCI6MTcwNTQ1MjY4M30.-MUaWgxxXoVG_tPEqCk9uVD0t05WEomV_TxkAWr6fAY

### Get fresh JWT 
GET http://localhost:3001/v1/tokens
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFzQGFzZC5jb20iLCJpYXQiOjE3MDU0NDUxMjgsImV4cCI6MTcwODAzNzEyOH0.51GFfEDAPTVvbP5Q7pwWxShOK9qdBMBzuOuzuahFeSU

### Reset Paasword
POST http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email": "as@asd.com",
    "password": "bleh"
}
