### User sign up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
    "name": "ken",
    "phone": 122121212,
    "email": "as@asd.com",
    "password": "bleh"
}

### User sign in endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
    "email": "as@asd.com",
    "password": "bleh"
}

### Get a user profile endpoint
GET http://localhost:3001/v1/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFzQGFzZC5jb20iLCJpYXQiOjE3MTI2OTQyMzEsImV4cCI6MTcxMjY5NTEzMX0.7i35pP_vOAUlCFqPz3PipNkDYcPNzpJuKyI24OjJqB4

### Get access JWT 
GET http://localhost:3001/v1/tokens
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFzQGFzZC5jb20iLCJpYXQiOjE3MTEzODIxMDAsImV4cCI6MTcxMzk3NDEwMH0.7jD38KIwKnTkzMwOxLWFeeq0yjafKE61-BuM7bgDrnI

### Reset Password
POST http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email": "as@asd.com",
    "password": "bleh"
}
